### ISSUE TITLE
Sources not loading properly 

### ISSUE THREAD

**Issue by akshatgoel07** [supermemoryai/opensearch-ai#10]
- Sources are scraped with tags, like strong
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/ab38e64a-442b-4107-b746-1354ab4eef78">

**Comment by akshatgoel07** [comment]
More results is also not clickable.
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/944d8ae9-4334-4f62-ba06-a9b54b9fb3c2">

**Comment by dhifafaz** [comment]
hey can i get a tutorial from you on how to deploy it? im a bit unfamiliar with next js

**Comment by MaheshtheDev** [comment]
#21 , this PR will fix the issue with new added component for displaying all web search references

**Comment by MaheshtheDev** [comment]
closing as #21 is merged
