### ISSUE TITLE
Memories not getting saved

### ISSUE THREAD

**Issue by TitasDas** [supermemoryai/opensearch-ai#13]
When I try to add a memory through the saved memories button right on top, the website I am trying to add doesn't get added. Does it require a mem0 api_key to be configured? Please let me know if I am using this wrong. Thanks in advance.

**Comment by MaheshtheDev** [comment]
Are you running in local development env? if so you need follow env variables in `.env` file
```
BACKEND_SECURITY_KEY=""
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
SEARCH_API_KEY=""
MEM0_API_KEY=""
OPENAI_API_KEY=""
```

**Comment by TitasDas** [comment]
Thanks for responding. This was when I ran it directly using [opensearch-ai.pages.dev](https://opensearch-ai.pages.dev/). From your answer I am guessing there isn't a stock set of keys that would allow it run in its original state when running through the website then?

**Comment by TitasDas** [comment]
Also I understand how to get the following keys, where/how can I get the rest? :

```
MEM0_API_KEY=""
OPENAI_API_KEY=""
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
```

**Comment by MaheshtheDev** [comment]
for using opensearch-ai.pages.dev, you don't need any set of keys or anything. Regarding, memories being saved, we are looking into it

**Comment by Dhravya** [comment]
Hi @TitasDas, for memory issues, can you send me the prompt you used, what was expected to get saved and what actually did get saved?

**Comment by TitasDas** [comment]
Thanks. 
I tried adding a url through the website. There is a button called add and I used that to enter a url of a website that I wanted to be used as context.

**Comment by TitasDas** [comment]
> for using opensearch-ai.pages.dev, you don't need any set of keys or anything. Regarding, memories being saved, we are looking into it

For the .dev page we don't need the keys however for running it locally and testing we may do. In the case of the latter how do I get the keys?

**Comment by MaheshtheDev** [comment]
SEARCH_API_KEY= from brave search API
MEM0_API_KEY= mem0 api
BACKEND_SECURITY_KEY="somerandomstring"
GOOGLE_CLIENT_ID=google oauth here "https://developers.google.com/identity/protocols/oauth2"
GOOGLE_CLIENT_SECRET= get it from here "https://developers.google.com/identity/protocols/oauth2"
OPENAI_API_KEY="openai API key" from the openAI account settings

you can google all these and get the api keys from there respective sites

**Comment by TitasDas** [comment]
Was essentially looking for the `BACKEND_SECURITY_KEY`
