### ISSUE TITLE
Extra Close Button in Saved Memory Modal

### ISSUE THREAD

**Issue by Arindam200** [supermemoryai/opensearch-ai#14]
## Description
In the Saved Memory modal, there's an extra "Close" button. Since we already have an 'X' button to close the modal, the additional "Close" button is unnecessary and redundant.

## Steps to Reproduce
1. Navigate to the Saved Memory section.
2. Open the Saved Memory modal.
3. Observe the presence of both an 'X' button and a "Close" button.

## Expected Behavior
The modal should only have one option to close it, preferably the 'X' button in the top-right corner.

## Actual Behavior
The modal currently has both an 'X' button and a "Close" button.

## Screenshot
![image](https://github.com/user-attachments/assets/2975e775-8aeb-48cc-b228-d14a71e04d23)

## Possible Solution
Remove the "Close" button from the modal, leaving only the 'X' button for closing the modal.

## Note
I would like to work on this

**Comment by MaheshtheDev** [comment]
@Arindam200 , sure thanks for the catch. Issue is assigned to you

**Comment by Arindam200** [comment]
Thanks, Will make a PR shortly
