### ISSUE TITLE
Improve Form Handling in `chatpage.tsx`

### ISSUE THREAD

**Issue by Arindam200** [supermemoryai/opensearch-ai#15]
## Description
The current implementation of form handling in `chatpage.tsx` is causing issues with hot reloading. The form submission logic is embedded directly within the component, which leads to unnecessary re-renders and potential performance issues during development.

## Steps to Reproduce
1. Navigate to the chat page.
2. Make changes to the form submission logic in `chatpage.tsx`.
3. Observe that hot reloading causes the entire component to re-render, leading to a suboptimal development experience.

## Expected Behavior
Form submission logic should be handled by separate functions to avoid unnecessary re-renders and improve the hot reloading experience.

## Actual Behavior
The form submission logic is embedded within the component, causing the entire component to re-render during hot reloads.

## Possible Solution
Refactor the form handling logic by creating separate functions for handling `onSubmit` events. This will help in isolating the form submission logic and prevent unnecessary re-renders during hot reloading.

## Additional Information
I would like to work on this

**Comment by Dhravya** [comment]
Thanks! Yeah, There's one more issue that there's no loading indicator on submit right now.
