### ISSUE TITLE
Allow `/?q={query}`

### ISSUE THREAD

**Issue by ThatOneCalculator** [supermemoryai/opensearch-ai#2]
If a `q={query}` parameter is allowed, that would enable people to add OpenSearch AI as a proper browser search engine!

**Comment by Dhravya** [comment]
hmm yes! 
Before that, i feel like the number one priority is conversational flows and slight UI improvements. I am kinda busy with supermemory stuff right now, actively looking for contributors and any help :)

**Comment by mhetreayush** [comment]
@Dhravya are we moving forward with this as of now? Or considering the comments you are gonna give it another thought?

**Comment by andrebrito16** [comment]
@Dhravya I'm currently working on this. Expect PR on the next 1 or 2 days.

**Comment by andrebrito16** [comment]
@Dhravya solved on PR #19
